#!/usr/bin/env bash

echo "Uninstalling..."

echo "Deleting .bash_profile"
unlink ~/.bash_profile

echo "Deleting .bashrc"
unlink ~/.bashrc

echo "Deleting .bash_aliases"
unlink ~/.bash_aliases

echo "Deleting .bash_extras"
unlink ~/.bash_extras

echo "Deleting .gitconfig"
unlink ~/.gitconfig
